# Generated by Django 4.1.3 on 2022-12-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_carousel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
