# Generated by Django 4.1.3 on 2022-12-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_posts_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
    ]
