# Generated by Django 4.1.3 on 2022-12-17 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_posts_price'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='posts',
            index_together={('id', 'slug')},
        ),
    ]
