# Generated by Django 4.1.4 on 2022-12-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vk_or_telegram',
            field=models.CharField(default='vk.com', max_length=255, verbose_name='Ссылка для связи'),
        ),
    ]
