# Generated by Django 4.1.4 on 2022-12-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_orderitem_quantity_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='version_of_platform',
            field=models.CharField(default='PS4', max_length=55, verbose_name='Версия для label'),
        ),
    ]
