# Generated by Django 4.1.4 on 2023-01-04 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_posts_version_of_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
