# Generated by Django 4.1.4 on 2023-01-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
