# Generated by Django 4.1.4 on 2023-01-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_posts_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='release_date',
            field=models.DateTimeField(default='2023-01-01'),
        ),
    ]
