version: '3.10'

services:
  django:
    restart: always
    build: .
    container_name: ps_store_django
    command: >
      sh -c "python manage.py makemigrations && 
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/ps_store
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  postgres:
    restart: always
    image: postgres:15.1-alpine
    container_name: ps_store_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
    env_file:
      .env


volumes:
  postgres_data: